### ISSUE TITLE
When updating personal profile, it does not register my cell phone number when I input it 

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#63]
It keeps registering this number as the default: 214 748 3647

**Comment by duncangraham** [comment]
this is @freindst's territory. Any idea what's going on here Blade?

**Comment by freindst** [comment]
I made a test. It is my fault when design the user table. I set phone number as INTEGER type, and numbers over 2 billion may exceed the data field. I have changed it to STRING type, and the problem has been solved. The bad news is database has to be recreated.

**Comment by markstm17** [comment]
@freindst I reopened this issue because I have had the same problem. It still doesn't save the number and it saves them phone number that I have listed above

**Comment by freindst** [comment]
I guess there is still something wrong with the code, because it is the maximum number of an integer number. So, somewhere the data is being sent with integer. I am looking for the problem.

**Comment by freindst** [comment]
On my local server, it runs correctly. I compared with my local server and online server, and then I noticed that argobus is still treat the phone field as an integer, though it is defined as a string in the user model:
![image](https://cloud.githubusercontent.com/assets/13219475/9089141/597d7e84-3b59-11e5-842f-60573caaab83.png)
The evident is if it is a string type, I can store string like "abcd", just as my local server:
![image](https://cloud.githubusercontent.com/assets/13219475/9089191/8235ef00-3b59-11e5-9d2b-f07a2ba50876.png)

While in Argobus, when I try to save "abcd" in the phone field, the result will be:
![image](https://cloud.githubusercontent.com/assets/13219475/9089223/a7a06586-3b59-11e5-8218-df2370924c78.png)

So, I think the solution is to recreate the database. @duncangraham , would you deal with it?
Maybe we can think about how to immigrate database in near future.

**Comment by duncangraham** [comment]
haha yea, I can recreate the production database.

**Comment by duncangraham** [comment]
deleted and restarted the production DB-- wanna test again @markstm17?

**Comment by markstm17** [comment]
Yeah I'll test it out again and I'll respond in a minute

**Comment by duncangraham** [comment]
did you end up testing this @markstm17?

**Comment by freindst** [comment]
@markstm17 , @duncangraham , I have tested this issue. It works now.
